drop table if exists t_user;

create table t_user (
	id bigint generated by default as identity,
    user_name varchar(64) not null unique,
    password varchar(64) not null,
    birth_day timestamp not null,
    created_at timestamp not null,
    updated_at timestamp null,
    primary key (id)
);