drop table if exists t_user;

create table t_user (
	id bigint generated by default as identity,
    user_name varchar(64) not null unique,
    password varchar(64) not null,
    birth_day timestamp not null,
    created_at timestamp not null,
    updated_at timestamp null,
    primary key (id)
);

insert into t_user(user_name, password, birth_day, created_at, updated_at) values('a','a', now(), now(), now());
insert into t_user(user_name, password, birth_day, created_at, updated_at) values('b','b', now(), now(), now());
insert into t_user(user_name, password, birth_day, created_at, updated_at) values('c','c', now(), now(), now());
insert into t_user(user_name, password, birth_day, created_at, updated_at) values('d','d', now(), now(), now());
insert into t_user(user_name, password, birth_day, created_at, updated_at) values('e','e', now(), now(), now());